services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql+asyncpg://local:local@db:5432/net_db
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "python -c 'import asyncio; from database import create_tables; asyncio.run(create_tables())'
      && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=net_db
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local -d net_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: