"""add mixins

Revision ID: 265b02413e79
Revises: 7fd225ccc03d
Create Date: 2025-10-28 23:28:55.558848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func


# revision identifiers, used by Alembic.
revision: str = '265b02413e79'
down_revision: Union[str, Sequence[str], None] = '7fd225ccc03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=func.now(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=func.now(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), default=False, nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index('ix_users_is_deleted', 'users', ['is_deleted'])

    op.execute("UPDATE users SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE users SET is_deleted = FALSE WHERE is_deleted IS NULL")

    op.alter_column('users', 'created_at', nullable=False)
    op.alter_column('users', 'updated_at', nullable=False)
    op.alter_column('users', 'is_deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_is_deleted', table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
